on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release
  release:
    types: [created]
name: Build Release
env:
  GO_VERSION: "~1"
  TASK_VERSION: v3.41.0
  TASK_SUM: 0a2595f7fa3c15a62f8d0c244121a4977018b3bfdec7c1542ac2a8cf079978b8
jobs:
  release:
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
    #
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        check-latest: true
    #
    - name: Tooling(checksum)
      run: go install github.com/mdouchement/checksum@master
    - name: Tooling(Taskfile)
      run: |
        curl -LO https://github.com/go-task/task/releases/download/${{ env.TASK_VERSION }}/task_linux_amd64.tar.gz && \
        echo "${{ env.TASK_SUM }}  task_linux_amd64.tar.gz" | sha256sum -c && \
        tar -xf task_linux_amd64.tar.gz && \
        cp task /usr/local/bin/
    #
    - name: Checkout code
      uses: actions/checkout@v4
    #
    - name: Build binaries
      run: task build-all
    #
    - name: Update release
      run: go run .github/workflows/release.go
      env:
        # secrets.GITHUB_TOKEN is created by GH action and is limited to the repository
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
